# Generated by Django 5.2.8 on 2026-02-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tutor', 'Tutor'), ('learner', 'Learner')], default='learner', max_length=20),
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(max_length=150)),
                ('experience_years', models.IntegerField()),
                ('skills', models.TextField()),
                ('teaching_level', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('cv', models.FileField(upload_to='tutor_cvs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
