# Generated by Django 5.2.8 on 2026-02-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role_tutorapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorapplication",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="tutorapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="pending"),
                fields=("user",),
                name="unique_pending_tutor_application_per_user",
            ),
        ),
    ]

