# Generated by Django 5.2.8 on 2026-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_active_course_is_published_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
