# Generated by Django 5.2.10 on 2026-03-23 16:44

from django.db import migrations, models


def populate_sequence_order(apps, schema_editor):
    InterviewResponse = apps.get_model('ai_engine', 'InterviewResponse')
    assessment_ids = (
        InterviewResponse.objects.order_by()
        .values_list('assessment_id', flat=True)
        .distinct()
    )
    for assessment_id in assessment_ids:
        responses = InterviewResponse.objects.filter(assessment_id=assessment_id).order_by('id')
        for index, response in enumerate(responses, start=1):
            response.sequence_order = index
            response.save(update_fields=['sequence_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_interviewassessment_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewresponse',
            options={'ordering': ['sequence_order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='interviewresponse',
            name='unique_question_per_assessment',
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='sequence_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(populate_sequence_order, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='interviewresponse',
            name='question_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
