# Generated by Django 5.2.8 on 2026-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_alter_interviewresponse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewassessment',
            name='interview_language',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
