# Generated by Django 5.2.10 on 2026-02-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('course', 'Course'), ('conversation', 'Conversation')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_at'],
            },
        ),
    ]
