# Generated by Django 5.2.8 on 2026-03-25 15:30

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_shorten_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(default=certificates.models.generate_certificate_id, editable=False, max_length=24, unique=True),
        ),
    ]
